# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(choices=[('Analgesico', 'Analgesico'), ('Androgenos', 'Androgenos')], default=0, max_length=60)),
                ('prescripcion', models.CharField(choices=[('Con Receta', 'Con Receta'), ('Sin Receta', 'Sin Receta')], default=0, max_length=60)),
                ('tipo', models.CharField(choices=[('Pastillas', 'Pastillas'), ('Jarabe', 'Jarabe'), ('Gotas', 'Gotas')], default=0, max_length=60)),
                ('concentracion_gramos', models.CharField(max_length=60)),
                ('cantidad', models.CharField(max_length=60)),
                ('laboratorio', models.CharField(max_length=60)),
                ('fecha_vencimiento', models.DateField()),
                ('stock', models.BooleanField(default=False)),
            ],
        ),
    ]
