# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(choices=[('Analgesico', 'Analgesico'), ('Androgenos', 'Androgenos')], default='Null', max_length=60)),
                ('prescripcion', models.CharField(choices=[('Con Receta', 'Con Receta'), ('Sin Receta', 'Sin Receta')], default=0, max_length=60)),
                ('tipo', models.CharField(choices=[('Pastillas', 'Pastillas'), ('Jarabe', 'Jarabe'), ('Gotas', 'Gotas')], default=0, max_length=60)),
                ('concentracion_gramos', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('cantidad', models.CharField(max_length=60)),
                ('laboratorio', models.CharField(max_length=60)),
                ('fecha_vencimiento', models.DateField()),
                ('stock', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pedir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnv.Medicamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificarIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnv.Medicamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificarRestiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnv.Medicamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donacion',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnv.Medicamento'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
