# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnv', '0002_auto_20170523_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
