# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnv', '0003_auto_20170523_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(default='', max_length=60),
        ),
    ]
