# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-05 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnv', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verificador',
            field=models.BooleanField(default=False),
        ),
    ]
