# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentodonado',
            name='donacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_donados', to='donaciones.Donacion'),
        ),
        migrations.AlterField(
            model_name='medicamentodonado',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
    ]
