# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0002_auto_20170622_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedir',
            new_name='Pedido',
        ),
    ]
