# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0003_auto_20170622_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.CharField(default='24', max_length=60),
            preserve_default=False,
        ),
    ]
