# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0004_pedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentodonado',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
